// This file is autogenerated by /generate_from_api.mjs
// Do not edit this file directly - it will be overwritten

export type ProfessionTypes =
  | 'Elementalist'
  | 'Engineer'
  | 'Guardian'
  | 'Mesmer'
  | 'Necromancer'
  | 'Ranger'
  | 'Revenant'
  | 'Thief'
  | 'Warrior';

export type EliteSpecTypes =
  | 'Amalgam'
  | 'Antiquary'
  | 'Berserker'
  | 'Bladesworn'
  | 'Catalyst'
  | 'Chronomancer'
  | 'Conduit'
  | 'Daredevil'
  | 'Deadeye'
  | 'Dragonhunter'
  | 'Druid'
  | 'Evoker'
  | 'Firebrand'
  | 'Galeshot'
  | 'Harbinger'
  | 'Herald'
  | 'Holosmith'
  | 'Luminary'
  | 'Mechanist'
  | 'Mirage'
  | 'Paragon'
  | 'Reaper'
  | 'Renegade'
  | 'Ritualist'
  | 'Scourge'
  | 'Scrapper'
  | 'Soulbeast'
  | 'Specter'
  | 'Spellbreaker'
  | 'Tempest'
  | 'Troubadour'
  | 'Untamed'
  | 'Vindicator'
  | 'Virtuoso'
  | 'Weaver'
  | 'Willbender';

const PROFESSIONS: Record<ProfessionTypes, EliteSpecTypes[]> = {
  Elementalist: ['Tempest', 'Weaver', 'Catalyst', 'Evoker'],
  Engineer: ['Scrapper', 'Holosmith', 'Mechanist', 'Amalgam'],
  Guardian: ['Dragonhunter', 'Firebrand', 'Willbender', 'Luminary'],
  Mesmer: ['Chronomancer', 'Mirage', 'Virtuoso', 'Troubadour'],
  Necromancer: ['Reaper', 'Scourge', 'Harbinger', 'Ritualist'],
  Ranger: ['Druid', 'Soulbeast', 'Untamed', 'Galeshot'],
  Revenant: ['Herald', 'Renegade', 'Vindicator', 'Conduit'],
  Thief: ['Daredevil', 'Deadeye', 'Specter', 'Antiquary'],
  Warrior: ['Berserker', 'Spellbreaker', 'Bladesworn', 'Paragon'],
};
export default PROFESSIONS;
