// This file is autogenerated by /generate_from_api.mjs
// Do not edit this file directly - it will be overwritten

export type RacesTypes = 'Asura' | 'Charr' | 'Human' | 'Norn' | 'Sylvari';

const RACES: RacesTypes[] = ['Asura', 'Charr', 'Human', 'Norn', 'Sylvari'];
export default RACES;
