version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels: []
    schedule:
      interval: cron
      cronjob: 0 17 5 * *
    groups:
      github-actions:
        patterns:
          - '*'
