export default {
  fonts: {
    gw2: {
      body:
        'Menomonia, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
      heading:
        'Menomonia, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
    },
  },
  fontWeights: {
    gw2: {
      body: 400,
      heading: 700,
    },
  },
  lineHeights: {
    gw2: {
      body: 1.46429,
      heading: 1.16667,
    },
  },

  colors: {
    text: '#000',
    primary: '#2b6cb0',
    primaryDark: '#183c63',
    primaryLight: '#6ba1db',
    error: '#dd2c00',

    gw2: {
      details: {
        title: '#eebb66',
        muted: 'rgba(255,255,255,0.7)',
        bonus: '#5599ff',
        bonusInactive: '#aaa',
        attribute: '#30ad37',
        flavor: '#a4c7c9',
        abilityType: '#efdf80',
      },

      gold: '#e5be45',
      silver: '#cbcac8',
      copper: '#a0673a',

      attribute: '#aaa',
      attributeDark: '#7a7a7a',
      attributeLight: '#e0e0e0',

      profession: {
        elementalist: '#f68a87',
        elementalistDark: '#dc423e',
        elementalistLight: '#f6bebc',
        engineer: '#d09c59',
        engineerDark: '#87581d',
        engineerLight: '#e8bc84',
        guardian: '#72c1d9',
        guardianDark: '#186885',
        guardianLight: '#bce8fd',
        mesmer: '#b679d5',
        mesmerDark: '#69278a',
        mesmerLight: '#d09eea',
        necromancer: '#52a76f',
        necromancerDark: '#2c9d5d',
        necromancerLight: '#bfe6d0',
        ranger: '#8cdc82',
        rangerDark: '#67a833',
        rangerLight: '#d2f6bc',
        revenant: '#d16e5a',
        revenantDark: '#a66356',
        revenantLight: '#e4aea3',
        thief: '#c08f95',
        thiefDark: '#974550',
        thiefLight: '#dec6c9',
        warrior: '#ffd166',
        warriorDark: '#caaa2a',
        warriorLight: '#fff2a4',
      },

      rarity: {
        legendary: '#4c139d',
        legendaryDark: '#230949',
        legendaryLight: '#8037e6',
        ascended: '#fb3e8d',
        ascendedDark: '#dc045e',
        ascendedLight: '#fdafd0',
        exotic: '#ffa405',
        exoticDark: '#a36700',
        exoticLight: '#ffcb70',
        rare: '#fcd00b',
        rareDark: '#a28402',
        rareLight: '#fee472',
        masterwork: '#1a9306',
        masterworkDark: '#0b3b02',
        masterworkLight: '#36f514',
        fine: '#62A4DA',
        fineDark: '#2b77b6',
        fineLight: '#bdd9ef',
        basic: '#000',
        basicDark: '#000',
        basicLight: '#333',
        junk: '#aaa',
        junkDark: '#7a7a7a',
        junkLight: '#e0e0e0',
      },

      effect: {
        aura: '#329ead',
        auraDark: '#1c575f',
        auraLight: '#71cad6',
        boon: '#d67400',
        boonDark: '#7a4300',
        boonLight: '#ffac47',
        condition: '#d23a30',
        conditionDark: '#86241d',
        conditionLight: '#e5908a',
        control: '#7e6961',
        controlDark: '#453a35',
        controlLight: '#af9e97',
        consumable: '#329ead',
        consumableDark: '#1c575f',
        consumableLight: '#71cad6',
        common: '#329ead',
        commonDark: '#1c575f',
        commonLight: '#71cad6',
        mistlockInstability: '#b99700',
        mistlockInstabilityDark: '#524300',
        mistlockInstabilityLight: '#ffd61f',
      },

      race: {
        asura: '#7e2aff',
        asuraDark: '#5200cc',
        asuraLight: '#c299ff',
        charr: '#9b0303',
        charrDark: '#3c0101',
        charrLight: '#fa0f0f',
        human: '#fcd12b',
        humanDark: '#c9a103',
        humanLight: '#fdea9b',
        norn: '#5f9ffe',
        nornDark: '#0162f4',
        nornLight: '#c2daff',
        sylvari: '#368103',
        sylvariDark: '#112801',
        sylvariLight: '#63ef06',
      },
    },
  },

  zIndices: {
    tooltip: 1500,
  },
};
