export interface ItemStatNames {
  BERSERKER: string;
  ZEALOT: string;
  SOLDIER: string;
  FORSAKEN: string;
  VALKYRIE: string;
  HARRIER: string;
  PALADIN: string;
  COMMANDER: string;
  DEMOLISHER: string;
  SWASHBUCKLER: string;
  MARAUDER: string;
  AVATAR: string;
  SEEKER: string;
  DESTROYER: string;
  VIGILANT: string;
  CRUSADER: string;
  WANDERER: string;
  DIVINER: string;
  WIZARD: string;
  VIPER: string;
  GRIEVING: string;
  SAGE: string;
  MARSHAL: string;
  MENDER: string;
  CAPTAIN: string;
  RAMPAGER: string;
  ASSASSIN: string;
  DEADSHOT: string;
  SERAPH: string;
  KNIGHT: string;
  CAVALIER: string;
  NOMAD: string;
  SETTLER: string;
  GIVER: string;
  TRAILBLAZER: string;
  MINSTREL: string;
  BARBARIAN: string;
  SENTINEL: string;
  SHAMAN: string;
  SINISTER: string;
  CARRION: string;
  RABID: string;
  DIRE: string;
  APOSTATE: string;
  PLAGUEDOCTOR: string;
  BRINGER: string;
  CLERIC: string;
  MAGI: string;
  APOTHECARY: string;
  CELESTIAL: string;
}

const itemStatNames: ItemStatNames = {
  BERSERKER: 'Berserker',
  ZEALOT: 'Zealot',
  SOLDIER: 'Soldier',
  FORSAKEN: 'Forsaken',
  VALKYRIE: 'Valkyrie',
  HARRIER: 'Harrier',
  PALADIN: 'Paladin',
  COMMANDER: 'Commander',
  DEMOLISHER: 'Demolisher',
  SWASHBUCKLER: 'Swashbuckler',
  MARAUDER: 'Marauder',
  AVATAR: 'Avatar',
  SEEKER: 'Seeker',
  DESTROYER: 'Destroyer',
  VIGILANT: 'Vigilant',
  CRUSADER: 'Crusader',
  WANDERER: 'Wanderer',
  DIVINER: 'Diviner',
  WIZARD: 'Wizard',
  VIPER: 'Viper',
  GRIEVING: 'Grieving',
  SAGE: 'Sage',
  MARSHAL: 'Marshal',
  MENDER: 'Mender',
  CAPTAIN: 'Captain',
  RAMPAGER: 'Rampager',
  ASSASSIN: 'Assassin',
  DEADSHOT: 'Deadshot',
  SERAPH: 'Seraph',
  KNIGHT: 'Knight',
  CAVALIER: 'Cavalier',
  NOMAD: 'Nomad',
  SETTLER: 'Settler',
  GIVER: 'Giver',
  TRAILBLAZER: 'Trailblazer',
  MINSTREL: 'Minstrel',
  BARBARIAN: 'Barbarian',
  SENTINEL: 'Sentinel',
  SHAMAN: 'Shaman',
  SINISTER: 'Sinister',
  CARRION: 'Carrion',
  RABID: 'Rabid',
  DIRE: 'Dire',
  APOSTATE: 'Apostate',
  PLAGUEDOCTOR: 'Plaguedoctor',
  BRINGER: 'Bringer',
  CLERIC: 'Cleric',
  MAGI: 'Magi',
  APOTHECARY: 'Apothecary',
  CELESTIAL: 'Celestial',
}

export default itemStatNames;