// This file is autogenerated by /generate_from_api.mjs
// Do not edit this file directly - it will be overwritten

import type { Translation } from '.';
import type { ProfessionTypes, EliteSpecTypes } from '../data/professions';

const TRANSLATIONS_PROFESSIONS: Record<
  ProfessionTypes | EliteSpecTypes,
  Translation
> = {
  Berserker: { zh: '狂战士' },
  Bladesworn: {
    de: 'Klingengeschworener',
    es: 'Jurafilos',
    fr: 'Jurelame',
    zh: '誓刃斗士',
  },
  Catalyst: {
    de: 'Katalysierer',
    es: 'Catalizador',
    fr: 'Catalyseur',
    zh: '元晶师',
  },
  Chronomancer: {
    de: 'Chronomant',
    es: 'Cronomante',
    fr: 'Chronomancien',
    zh: '时空术士',
  },
  Daredevil: {
    de: 'Draufgänger',
    es: 'Temerario',
    fr: 'Fracasseur',
    zh: '独行侠',
  },
  Deadeye: { de: 'Scharfschütze', es: 'Certero', fr: 'Sniper', zh: '神枪手' },
  Dragonhunter: {
    de: 'Drachenjäger',
    es: 'Cazadragones',
    fr: 'Draconnier',
    zh: '猎龙者',
  },
  Druid: { de: 'Druide', es: 'Druida', fr: 'Druide', zh: '德鲁伊' },
  Elementalist: {
    de: 'Elementarmagier',
    es: 'Elementalista',
    fr: 'Élémentaliste',
    zh: '元素使',
  },
  Engineer: { de: 'Ingenieur', es: 'Ingeniero', fr: 'Ingénieur', zh: '工程师' },
  Firebrand: {
    de: 'Aufwiegler',
    es: 'Abrasador',
    fr: 'Incendiaire',
    zh: '燃火者',
  },
  Guardian: { de: 'Wächter', es: 'Guardián', fr: 'Gardien', zh: '守护者' },
  Harbinger: { de: 'Vorbote', es: 'Augurador', fr: 'Augure', zh: '先驱者' },
  Herald: { de: 'Herold', es: 'Heraldo', fr: 'Héraut', zh: '预告者' },
  Holosmith: {
    de: 'Holoschmied',
    es: 'Holoartesano',
    fr: 'Holographiste',
    zh: '全息师',
  },
  Mechanist: {
    de: 'Mech-Lenker',
    es: 'Mechanista',
    fr: 'Mechamancien',
    zh: '玉偃师',
  },
  Mesmer: { es: 'Hipnotizador', fr: 'Envoûteur', zh: '幻术师' },
  Mirage: { de: 'Illusionist', es: 'Quimérico', zh: '幻象术士' },
  Necromancer: {
    de: 'Nekromant',
    es: 'Nigromante',
    fr: 'Nécromant',
    zh: '唤灵师',
  },
  Ranger: { de: 'Waldläufer', es: 'Guardabosques', fr: 'Rôdeur', zh: '游侠' },
  Reaper: { de: 'Schnitter', es: 'Segador', fr: 'Faucheur', zh: '夺魂者' },
  Renegade: { de: 'Abtrünniger', es: 'Renegado', fr: 'Renégat', zh: '龙魂使' },
  Revenant: { de: 'Wiedergänger', es: 'Retornado', zh: '魂武者' },
  Scourge: { de: 'Pestbringer', es: 'Azotador', fr: 'Fléau', zh: '灾厄师' },
  Scrapper: {
    de: 'Schrotter',
    es: 'Chatarrero',
    fr: 'Mécatronicien',
    zh: '机械师',
  },
  Soulbeast: {
    de: 'Seelenwandler',
    es: 'Bestialma',
    fr: 'Animorphe',
    zh: '魂兽师',
  },
  Specter: { de: 'Phantom', es: 'Espectro', fr: 'Spectre', zh: '缚影者' },
  Spellbreaker: {
    de: 'Bannbrecher',
    es: 'Rompehechizos',
    fr: 'Brisesort',
    zh: '破法者',
  },
  Tempest: { de: 'Sturmbote', es: 'Tempestad', fr: 'Cataclyste', zh: '暴风使' },
  Thief: { de: 'Dieb', es: 'Ladrón', fr: 'Voleur', zh: '潜行者' },
  Untamed: {
    de: 'Ungezähmter',
    es: 'Indómito',
    fr: 'Indomptable',
    zh: '狂兽师',
  },
  Vindicator: {
    de: 'Rechtssuchender',
    es: 'Justiciero',
    fr: 'Justicier',
    zh: '裁决者',
  },
  Virtuoso: { de: 'Virtuose', fr: 'Virtuose', zh: '灵刃术士' },
  Warrior: { de: 'Krieger', es: 'Guerrero', fr: 'Guerrier', zh: '战士' },
  Weaver: { de: 'Weber', es: 'Tejedor', fr: 'Tissesort', zh: '编织者' },
  Willbender: {
    de: 'Willensverdreher',
    es: 'Subyugador',
    fr: 'Subjugueur',
    zh: '破锋者',
  },
};
export default TRANSLATIONS_PROFESSIONS;
