// This file is autogenerated by /generate_from_api.mjs
// Do not edit this file directly - it will be overwritten

import type { Translation } from '.';
import type { RacesTypes } from '../data/races';

const TRANSLATIONS_RACES: Record<RacesTypes, Translation> = {
  Asura: { zh: '阿苏拉' },
  Charr: { zh: '夏尔' },
  Human: { de: 'Mensch', es: 'Humano', fr: 'Humain', zh: '人类' },
  Norn: { zh: '诺恩' },
  Sylvari: { zh: '希尔瓦里' },
};
export default TRANSLATIONS_RACES;
