// This file is autogenerated by /generate_from_api.mjs
// Do not edit this file directly - it will be overwritten

export type ProfessionTypes =
  | 'Berserker'
  | 'Bladesworn'
  | 'Catalyst'
  | 'Chronomancer'
  | 'Daredevil'
  | 'Deadeye'
  | 'Dragonhunter'
  | 'Druid'
  | 'Elementalist'
  | 'Engineer'
  | 'Firebrand'
  | 'Guardian'
  | 'Harbinger'
  | 'Herald'
  | 'Holosmith'
  | 'Mechanist'
  | 'Mesmer'
  | 'Mirage'
  | 'Necromancer'
  | 'Ranger'
  | 'Reaper'
  | 'Renegade'
  | 'Revenant'
  | 'Scourge'
  | 'Scrapper'
  | 'Soulbeast'
  | 'Specter'
  | 'Spellbreaker'
  | 'Tempest'
  | 'Thief'
  | 'Untamed'
  | 'Vindicator'
  | 'Virtuoso'
  | 'Warrior'
  | 'Weaver'
  | 'Willbender';

const PROFESSIONS: Record<string, string[]> = {
  Elementalist: ['Tempest', 'Weaver', 'Catalyst'],
  Engineer: ['Scrapper', 'Holosmith', 'Mechanist'],
  Guardian: ['Dragonhunter', 'Firebrand', 'Willbender'],
  Mesmer: ['Chronomancer', 'Mirage', 'Virtuoso'],
  Necromancer: ['Reaper', 'Scourge', 'Harbinger'],
  Ranger: ['Druid', 'Soulbeast', 'Untamed'],
  Revenant: ['Herald', 'Renegade', 'Vindicator'],
  Thief: ['Daredevil', 'Deadeye', 'Specter'],
  Warrior: ['Berserker', 'Spellbreaker', 'Bladesworn'],
};
export default PROFESSIONS;
